require("arman.plugins.lazy")
require("arman.plugins.colorscheme")
require("arman.config.sets")
require("arman.config.keymap")
require("arman.plugins.treesitter")
require("arman.plugins.telescope")
require("arman.plugins.harpoon")
require("arman.plugins.lsp-config")
